global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'slack-monitor'

scrape_configs:
  - job_name: 'slack-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          service: 'slack-backend'
          version: 'v0.1'

